AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  PetStoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: petstore-swagger.json

  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::182219041700:role/service-role/hello_python-role-1cb3qfzr
      Handler: hello_world.hello_world
      CodeUri: ./hello_world.py
      Description: Hello World
      FunctionName: hello-lambda-python
    
Outputs:

    PetStoreAPI:
      Description: "Root API endpoint URL for Prod stage"
      Value: !Sub "https://${PetStoreAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"
      Export:
        Name: PetStoreAPIRoot